### ISSUE TITLE
MacOS issue

### ISSUE THREAD

**Issue by adrydez** [Rafostar/media-player-controller#5]
I tried to install this module on Electron application.
It works very well. On MacOS I have a problem.

Once run the funcion a message log in console say: 
```
Error: Media player exited with error code: 1
    at ChildProcess.<anonymous> (/Users/Shared/Reaper…roller/index.js:146)
    at Object.onceWrapper (events.js:291)
    at ChildProcess.emit (events.js:203)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:272)
```

I tried to run the command on bash and it works:
`/Applications/VLC.app/Contents/MacOS/VLC /HD Video/Videos/A.mp4`

and also by child process:
```javascript
var child_process = require ("child_process");
var proc= child_process.spawn ($('#vlcPath').val(), [$('#video').val() ], { shell: true });

proc.stderr.on ("data", (data) => {
    console.error ("VLC: " + data.toString ());
});

proc.stdout.on ("data", (data) => {
    console.log ("VLC: " + data.toString ());
});

proc.on ("exit", (code, signal) => {
    // Every code > 0 indicates an error.
    console.log ("VLC exited with code " + code);
});
```
and worked.

So, is there something that I wrong?
I'm here to test if you want to release new updates.

Thx

**Comment by Rafostar** [comment]
How did you launch the media-player-controller? Did you try to specify `cwd` with path to VLC install directory when creating new player object from its class?

**Comment by adrydez** [comment]
this is my function (copied from github):

```
           player = new PlayerController({
                app: '/Applications/VLC.app/Contents/MacOS/VLC',
                args: [],
                media: '/HD Video/Videos/A.mp4'
            });
            player.on('playback', console.log);
            
            player.on('playback-started', () => {
                console.log('Playback started. Player can now be controlled');      
            });
            
            player.on('app-exit', (code) => {
                istanceOpen = 0;
                console.log(`Media player closed. Exit code: ${code}`);
            });         
            
            player.launch(err => {
                if(err) return console.error(err);
                console.log('Media player launched');
            });
```
What I changed from your example (https://www.npmjs.com/package/vlc-player-controller) is this line:

`const PlayerController = require('media-player-controller');`
in
`const PlayerController = require('vlc-player-controller');`

because the package installed is npm i vlc-player-controller

I just realized that there is even a module called media-player-controller.
Maybe I have to install media-player-controller module and not vlc-player-controller?

Thanks

**Comment by Rafostar** [comment]
@adrydez 
I made only `media-player-controller`. Which is an universal controller that works with both `vlc` and `mpv` with some other media players support planned to be added in the future. I am maintaining it as one of main dependencies of my [playercast](https://github.com/Rafostar/playercast) app.

Some chinese guy forked it and decided to strip it from half of functionality that I implemented for some unknown reason and renamed it to `vlc-player-controller`. If you want to use his module instead of original one, then you are reporting an issue in a wrong github repository.

**Comment by adrydez** [comment]
I want to follow the ufficial version, so, let's go for your.
I have installed media-player-controller and then run my code on PC as previous with the fake version.
The surprise was this error: `unsupported player: C:\Program Files\VideoLAN\VLC\vlc.exe`
I have installed the latest version of VLC (3.0.11) at 64bit

Currently I have installed both versions, media-player-controller and vlc-player-controller
If I require vlc-player-controller library, VLC start without problems, with media-player-controller not.

How is possible.
On Mac I still have to test.

**Comment by Rafostar** [comment]
If you are using my (official version), then please read MY readme carefully. Especially [player-config](https://github.com/Rafostar/media-player-controller#player-config).

`app` property is just a media player name (`vlc` in your case). If you set it to something other than `mpv` or `vlc` you get the error you got just now.
`cwd` property is the custom path to **directory** where media player is located. You have to specify it only if you have not exported $PATH to your player binary globally in your OS.

Something like this on Windows:
```javascript
const PlayerController = require('media-player-controller');

var player = new PlayerController({
  app: 'vlc',
  cwd: 'C:\\Program Files\\VideoLAN\\VLC',
  media: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
});
```
Just make sure that `C:\\Program Files\\VideoLAN\\VLC` is really the dir where you have installed vlc.

BTW: `cwd` is a working directory for media player spawn, not your app!

Also please note that if you export `vlc` binary in your OS $PATH, then you won't have to specify cwd in your app, thus you can make your app more universal (work on all operating systems).

**Comment by adrydez** [comment]
Wow. It worked on windows. Very very well. Thanks
I tried on MacOS:

```
Uncaught TypeError: Cannot read property 'pid' of null
    at onSpawnError (/Users/Shared/Electron/APP/zenit1.0mac.app/Contents/Resources/app.asar/node_modules/media-player-controller/index.js:142)
    at PlayerController.launch (/Users/Shared/Electron/APP/zenit1.0mac.app/Contents/Resources/app.asar/node_modules/media-player-controller/index.js:157)
    at HTMLButtonElement.eval (eval at <anonymous> (index.php:3), <anonymous>:2565:20)
    at HTMLDocument.dispatch (<anonymous>:4:4351)
    at HTMLDocument.i (<anonymous>:4:328)
```
The configuration is this:

const PlayerController = require('media-player-controller');

```
var player = new PlayerController({
  app: 'vlc',
  cwd: '/Applications/VLC.app/Contents/MacOS/VLC',
  media: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
});
```
The path `/Applications/VLC.app/Contents/MacOS/VLC` is the real path where is the file to launch the process.

I hope this can help you to understand.

Regard this:
`Also please note that if you export vlc binary in your OS $PATH, then you won't have to specify cwd in your app, thus you can make your app more universal (work on all operating systems).`
I'm not so advanced to do it. :)

**Comment by Rafostar** [comment]
I have not tried this on Mac (cause I do not own one).

Could you try to remove `cwd` line in your script and then do in terminal:
```
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
```
and afterwards launch your script in the same terminal?

Also isn't `/Applications/VLC.app/Contents/MacOS/VLC` a complete path to binary (I am not sure)? If it is, then shouldn't the `cwd` simply be: `/Applications/VLC.app/Contents/MacOS`

Please try both methods and report if any of them worked for you.

**Comment by adrydez** [comment]
I'm using Electron on MacOS and I created the build directly in Windows.
But, about the binary file I'm really sure that the path it's ok.
In fact, I run the OS terminal in MacOS and insert these lines:
`alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'`
and then:
`vlc "/HD Video/Videos/A.mp4"`
and VLC started immediately.

For your module I tried with multple methods:
```
cwd: '/Applications/VLC.app/Contents/MacOS/VLC' // Uncaught TypeError: Cannot read property 'pid' of null
cwd:  '/Applications/VLC.app/Contents/MacOS' //  error spawn vlc ENOENT
cwd:  '/Applications/VLC.app' // error spawn vlc ENOENT
cwd: '/Applications/VLC.app' // error spawn vlc ENOENT
cwd: '/Applications/VLC' // error spawn vlc ENOENT
without cwd command  // error spawn vlc ENOENT
```
Any idea?

**Comment by Rafostar** [comment]
First `cwd` seems closest to be ok, I think. Send me the debug output:
```
DEBUG=mpc* node index.js
```
where `index.js` is obviously the main script in your app.

**Comment by adrydez** [comment]
I haven't the chance to do it on mac. I build Electron with asar on PC directly unsing Visual Studio Code and pass the app directly on Mac.
There is another way to do it via javascript?

**Comment by Rafostar** [comment]
You could add `debug.enabled = true;` somewhere in this module `index.js` file after `const debug` is declared. Not sure if this will provide much useful info, as debug was meant to observe the media player manipulation while it is working.

**Comment by adrydez** [comment]
I'm not so good to as you think. I tried to insert what you told me but without success.
Changing the error code, it game me this error message:
```
(unknown) Error: spawn vlc ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:264)
    at onErrorNT (internal/child_process.js:456)
    at processTicksAndRejections (internal/process/task_queues.js:81)
```

-------------------------------------------------------------
About the first row this is the piece of code of the error:
```
const err = errnoException(exitCode, syscall);
```
the second row at this function:
```
function onErrorNT(self, err) {
  self._handle.onexit(err);
}
```
and the last is this piece of code:
```
case 2: callback(args[0], args[1]); break;
```

I hope this can help you. If you want to have a chat, adrydez on Skype.
Let me know

**Comment by adrydez** [comment]
I did it!

After run `DEBUG=mpc* node index.js` this is the output of the terminal:
```
  mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:142
			if(!this.process.pid)
			                 ^

TypeError: Cannot read property 'pid' of null
    at onSpawnError (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:142:21)
    at PlayerController.launch (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:157:4)
    at Object.<anonymous> (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/index.js:23:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
At line 23 of index,js there is this line:
`player.launch(err => {
`

**Comment by Rafostar** [comment]
I pushed a commit, that should fix the "Cannot read property 'pid' of null" crash you have. The launching of VLC probably still won't work, be we should get a different error this time. Please pull my latest change and try running debug once again.

**Comment by adrydez** [comment]
I have installed again your module by `npm i media-player-controller` and this is the output:

```
mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +2ms
  mpc Forcing player english language +1ms
/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:142
			if(!this.process.pid)
			                 ^

TypeError: Cannot read property 'pid' of null
    at onSpawnError (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:142:21)
    at PlayerController.launch (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:157:4)
    at Object.<anonymous> (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/index.js:23:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47
```
I tried also to omit `cwd `command and the output is:

```
  mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
  mpc Spawned new player process +7ms
  mpc Error: spawn vlc ENOENT
  mpc     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
  mpc     at onErrorNT (internal/child_process.js:469:16)
  mpc     at processTicksAndRejections (internal/process/task_queues.js:84:21) +2ms
spawn vlc ENOENT
```

**Comment by Rafostar** [comment]
> I have installed again your module by npm i media-player-controller

No. The recent change is not uploaded to npm. You have to clone `media-player-controller` from github or at least replace `index.js` with the latest contents from github.

**Comment by adrydez** [comment]
OK. This is the new output
```
mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
  mpc Error: spawn ENOTDIR
  mpc     at ChildProcess.spawn (internal/child_process.js:407:11)
  mpc     at spawn (child_process.js:548:9)
  mpc     at PlayerController.launch (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:155:19)
  mpc     at Object.<anonymous> (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/index.js:23:12)
  mpc     at Module._compile (internal/modules/cjs/loader.js:1138:30)
  mpc     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
  mpc     at Module.load (internal/modules/cjs/loader.js:986:32)
  mpc     at Function.Module._load (internal/modules/cjs/loader.js:879:14)
  mpc     at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
  mpc     at internal/main/run_main_module.js:17:47 +3ms
spawn ENOTDIR
/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:161
		this.process.once('error', onSpawnError);
		             ^

TypeError: Cannot read property 'once' of null
    at PlayerController.launch (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:161:16)
    at Object.<anonymous> (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/index.js:23:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
```

**Comment by Rafostar** [comment]
`mpc Error: spawn ENOTDIR`

`ENOTDIR` means that your `cwd` path does not end with a directory where VLC is located. Could you verify in e.g. file manager?

**Comment by Rafostar** [comment]
I have one idea of a fix. I will let you know once I push it to github.

**Comment by adrydez** [comment]
I tried this code:
```
    var child_process = require('child_process');


    child_process.exec('/Applications/VLC.app/Contents/MacOS/VLC "/Volumes/HD video/video/1.mp4"',
    {
      //env: {"ATOM_SHELL_INTERNAL_RUN_AS_NODE":"1"}
    },
    function (error, stdout, stderr) {
      if (error) {
        console.error(`exec error: ${error}`);
        return;
      }
      console.log(`stdout: ${stdout}`);
      console.log(`stderr: ${stderr}`);
    });
```
and VLC run without problems

**Comment by Rafostar** [comment]
@adrydez 

OK. I did a small fix that might help. Please download latest code from github an launch with this config:
```javascript
const PlayerController = require('media-player-controller');

var player = new PlayerController({
  app: 'vlc',
  cwd: '/Applications/VLC.app/Contents/MacOS',
  media: 'http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/BigBuckBunny.mp4'
});
```

**Comment by adrydez** [comment]
Ok, copied the latest index.js and tested as you wrote. The error that gave me is this:
```
  mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +1ms
  mpc Spawned new player process +3ms
  mpc Error: spawn vlc ENOENT
  mpc     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
  mpc     at onErrorNT (internal/child_process.js:469:16)
  mpc     at processTicksAndRejections (internal/process/task_queues.js:84:21) +2ms
spawn vlc ENOENT
```
I tried also to give as cwd as before `/Applications/VLC.app/Contents/MacOS/VLC` and the log is:
```
No player binary found in: "/Applications/VLC.app/Contents/MacOS/VLC"
```

**Comment by Rafostar** [comment]
```javascript
var child_process = require ("child_process");
var proc= child_process.spawn ($('#vlcPath').val(), [$('#video').val() ], { shell: true });
```

You earlier said that something like the above worked for you.

The cwd path: `'/Applications/VLC.app/Contents/MacOS'` is probably the correct one.

Could you perhaps edit `spawnOpts` object in `index.js` at [line 126](https://github.com/Rafostar/media-player-controller/blob/3f2adadd56206189f8164198d019f570834b121b/index.js#L126) and add `shell: true` to it. Maybe this will help?

**Comment by adrydez** [comment]
Tried. Nope.
I modified index.js as 

```
		var spawnOpts = {
			stdio: ['ignore', 'pipe', 'ignore'],
			detached: launchOpts.detached,
			cwd: launchOpts.cwd,
			shell: true
		};
```
Error 127
```
mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
  mpc Spawned new player process +3ms
  mpc Media player process exit +5ms
Media player exited with error code: 127
```
I have a doubt.
If I digit in the browser `http://localhost:8080` the first thing that it asks is to insert username and password. If I don't digit nothing, the browser replies with 401 error.
Set the password in VLC for web service is mandatory. Maybe could be this the cause of errors?

**Comment by Rafostar** [comment]
No. `media-player-controller` sets the password to 'vlc' during launch.

In case of vlc the spawn command looks like this:
```javascript
spawn('VLC', [
    '--no-play-and-exit',
    '--no-qt-recentplay',
    '--qt-continue', '0',
    '--image-duration', '-1',
    '--extraintf', 'http',
    '--http-port', '8080',
    '--http-password', 'vlc',
    '/Volumes/HD video/video/1.mp4'
    ], {
        stdio: ['ignore', 'pipe', 'ignore'],
        detached: false,
        cwd: '/Applications/VLC.app/Contents/MacOS',
        shell: true,
        env: { ...process.env, LANG: 'C' }
    }
);
```

It works on Linux and Windows. I do not know why it doesn't work on MacOS. :disappointed:

**Comment by adrydez** [comment]
I follow always your instruction.
I noted that in /node_modules/media-player-controller/ in OSX by `npm i `is not present the subfolder node_modules with inside two subfolders called debug and ms (on Window yes). It is normal?
About '`--http-port', '8080',`
in all scripts I found only the value 9280, 8080 there isn't track of it.

**Comment by Rafostar** [comment]
> I noted that in /node_modules/media-player-controller/ in OSX by npm i is not present the subfolder node_modules with inside two subfolders called debug and ms (on Window yes). It is normal?

It would cause a crash of script right at node start, so its fine.

> in all scripts I found only the value 9280, 8080 there isn't track of it.

Should not matter unless some other application is using the same port. You can always try changing it (there is an option to set it when creating new PlayerController object).

Last time VLC actually started, but exited after 5ms with 127 code, so there is progress :+1: 
```
mpc Media player process exit +5ms
```

You can also try changing in `index.js`:
```javascript
stdio: ['ignore', 'pipe', 'ignore']
```
to
```javascript
stdio: 'inherit'
```

Maybe this will allow us to "see" the vlc error output in terminal.

**Comment by adrydez** [comment]
Tried:
```
mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:162
		this.process.stdout.setEncoding('utf8');
		                    ^

TypeError: Cannot read property 'setEncoding' of null
    at PlayerController.launch (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/node_modules/media-player-controller/index.js:162:23)
    at Object.<anonymous> (/Users/mymacaudio/Documents/ELECTRON/zenit1.0/index.js.js:36:12)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.Module._load (internal/modules/cjs/loader.js:879:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12)
    at internal/main/run_main_module.js:17:47

```

index.js:36:12:

> player.launch(err => {

**Comment by Rafostar** [comment]
Ah, remove all lines that contain `this.process.stdout`.

**Comment by adrydez** [comment]
KK. Just for summary:
I have removed:
```
		//this.process.stdout.setEncoding('utf8');
		//this.process.stdout.setNoDelay(true);

		/*if(debug.enabled)
		{
			this.process.stdout.on('data', debug);
			debug('Spawned new player process');
		}*/
```
> from line 162 to 169
```
		/*if(debug.enabled && this.process.stdout)
			this.process.stdout.removeListener('data', debug);*/
```
> from lines 228 and 229

It has generated:

```
  mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
  mpc Error: spawn vlc ENOENT
  mpc     at Process.ChildProcess._handle.onexit (internal/child_process.js:267:19)
  mpc     at onErrorNT (internal/child_process.js:469:16)
  mpc     at processTicksAndRejections (internal/process/task_queues.js:84:21) +4ms
spawn vlc ENOENT
```

independently if I set `shell:true` or not

**Comment by Rafostar** [comment]
You are still doing this on github version of `index.js`, right? And set `cwd: '/Applications/VLC.app/Contents/MacOS'` like you did before.

**Comment by adrydez** [comment]
Yes, I got the file here:
https://raw.githubusercontent.com/Rafostar/media-player-controller/master/index.js

then replace
`stdio: ['ignore', 'pipe', 'ignore']`
with
`stdio: 'inherit'`

Then deleted the rows as I wrote in the previous post.

My code is:
```
var player = new PlayerController({
    app: 'vlc',
    arg: [],
    cwd: '/Applications/VLC.app/Contents/MacOS',
    media: '/Volumes/HD video/video/1.mp4',
    shell:true
  });
```

**Comment by Rafostar** [comment]
We do not have `shell` property inside PlayerController. You have to add it in index.js like you did before.

**Comment by adrydez** [comment]
Including this piece of code at line 126,  (keeping the latest changes), (and leaving shell:true) from my index.js, it return:

```
  mpc Launching vlc... +0ms
  mpc Player media source: /Volumes/HD video/video/1.mp4 +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
/bin/sh: vlc: command not found
  mpc Media player process exit +8ms
Media player exited with error code: 127
```

**Comment by Rafostar** [comment]
Ok. leave the code as it is. And try doing:
```
alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
```
and run it once again in the same terminal where you input the alias command.

**Comment by adrydez** [comment]
Ok, wrote this code in terminal
> mymacaudio:zenit1.0 macaudio$ alias vlc='/Applications/VLC.app/Contents/MacOS/VLC'
> mymacaudio: zenit1.0 macaudio $ DEBUG=mpc* node index.js

It returns
```
  mpc Launching vlc... +0ms
  mpc Player media source: "/Volumes/HD video/video/1.mp4" +1ms
  mpc:socket Connecting web... +0ms
  mpc Player detached: false +3ms
  mpc Forcing player english language +0ms
/bin/sh: vlc: command not found
  mpc Media player process exit +12ms
Media player exited with error code: 127
```

**Comment by Rafostar** [comment]
It doesn't look like I will be able to help you any further. I wish I had a Mac to figure it out myself, but I don't. And it works on both Linux and Windows on my side. Sorry.
